import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Alexandria } from "next/font/google";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";
import NavBar from "./components/navbar/Navbar";
// import Footer from "./components/Footer";

const alexandria = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session =await auth();
  return (
    <SessionProvider session={session}>
    <html lang="en">
    <div className="absolute top-0 z-[-2] h-screen w-screen bg-white bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]"></div>
      <body className={alexandria.className}>
        <NavBar/>
        {children}
        {/* <Footer/> */}
        </body>
    </html>
    </SessionProvider>
  );
}
