import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Alexandria } from "next/font/google";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";
import NavBar from "./components/navbar/Navbar";

const alexandria = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session =await auth();
  return (
    <SessionProvider session={session}>
    <html lang="en">

      <body className={alexandria.className}>
        <NavBar/>
        {children}</body>
    </html>
    </SessionProvider>
  );
}
