import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en">

      <body className={inter.className}>
        <div className="flex">
            <div className="bg-violet-200 w-1/2">
                <NavBar/>
            </div>
            <div className="bg-red-200 w-1/2">
                {children}
            </div>
        </div>
        
        </body>
    </html>

  );
}
